---
deployment:
  tasks:
    - export DEPLOYPATH=/home/emprend1/indrastylo.uy/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    